# Generated by Django 4.2.7 on 2026-05-15 22:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('frequency', models.CharField(choices=[('once', 'One Time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='once', max_length=10)),
                ('scheduled_date', models.DateField(blank=True, help_text='Date for one-time announcements', null=True)),
                ('scheduled_time', models.TimeField(default=datetime.time(9, 0), help_text='Time to send announcement (HH:MM format)')),
                ('days_of_week', models.CharField(blank=True, help_text='Comma-separated: Mon,Tue,Wed,Thu,Fri,Sat,Sun (for weekly)', max_length=50)),
                ('day_of_month', models.IntegerField(blank=True, help_text='Day of month (1-31) for monthly announcements', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sent', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Announcements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessengerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=255, unique=True)),
                ('group_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messenger_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Messenger Groups',
            },
        ),
        migrations.CreateModel(
            name='AnnouncementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('messenger_timestamp', models.BigIntegerField(blank=True, null=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='messenger_bot.announcement')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger_bot.messengergroup')),
            ],
            options={
                'verbose_name_plural': 'Announcement Logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddField(
            model_name='announcement',
            name='groups',
            field=models.ManyToManyField(related_name='announcements', to='messenger_bot.messengergroup'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL),
        ),
    ]
